#!python3
import argparse
import os

parser = argparse.ArgumentParser()
parser.add_argument("path", help="path to directory")
args = parser.parse_args()

os.chdir(args.path)
for file in os.listdir():
    print("Processing: " + file)
    if file.endswith(".md"):
        with open(file) as f:
            content = f.readlines()

        # if the line starts with '\-' then remove the backslash
        for i, line in enumerate(content):
            if line.startswith("\\-") or line.startswith("\\#"):
                content[i] = line[1:]

        new_content = "".join(content)

        with open(file, "w") as f:
            f.write(new_content)
