#!/usr/bin/env python3
import argparse


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("first", help="The first string to compare")
    parser.add_argument("second", help="The second string to compare")
    args = parser.parse_args()

    if len(args.first) != len(args.second):
        print("The strings must be the same length.")

    diffs = 0
    counter = 0
    for char in args.first:
        if char != args.second[counter]:
            diffs += 1

        counter += 1

    print(f"{diffs} difference(s)")


if __name__ == "__main__":
    main()
