#!python3
import argparse
import logging

logging.basicConfig(level=logging.INFO)
logging.debug("Imports finished, about to define the command options with click.")

parser = argparse.ArgumentParser(
    description="Translate grades from percentage to letter."
)
parser.add_argument("grade", type=float, help="The grade to translate.")
parser.add_argument(
    "-c",
    "--curve",
    store_action=True,
    help="Show whether your grade is above or below average. Pass a the highest score in the class as an argument to show how much your grade was adjusted.",
)
args = parser.parse_args()


def main(grade: float, curve):
    """This script will tell you your letter grade based on your percentage grade."""
    logging.debug("Command options defined, about to run the main function.")
    logging.debug(f"The grade is: {grade}")

    if 97.0 <= grade <= 100.0:
        print("A+")
    elif 93.0 <= grade < 97.0:
        print("A")
    elif 90.0 <= grade < 93.0:
        print("A-")
    elif 87.0 <= grade < 90.0:
        print("B+")
    elif 83.0 <= grade < 87.0:
        print("B")
    elif 80.0 <= grade < 83.0:
        print("B-")
    elif 77.0 <= grade < 80.0:
        print("C+")
    elif 73.0 <= grade < 77.0:
        print("C")
    elif 70.0 <= grade < 73.0:
        print("C-")
    elif 67.0 <= grade < 70.0:
        print("D+")
    elif 63.0 <= grade < 67.0:
        print("D")
    elif 60.0 <= grade < 63.0:
        print("D-")
    elif 0.0 <= grade < 60.0:
        print("F")

    if curve:
        logging.debug("Curve option is set, about to calculate the curve grade.")
        logging.debug(f"The curve option value is: {curve}")
        # Show where in the class your grade is
        # Assume the class average is 85.0
        if grade >= 85.0:
            print("You are above average.")
        elif grade < 85.0:
            print("You are below average.")

        # Show how much your grade was adjusted
        curve = float(curve)
        if grade > curve:
            print("Your grade was adjusted by 0.0%.")
        elif grade <= curve:
            adjustment_amount = 100 - curve
            original_grade = grade - adjustment_amount
            logging.debug(f"The amount your grade was adjusted is: {adjustment_amount}")

            if grade == 100.0:
                print(
                    "You had the highest grade in the class. As such, you were the one who set the curve and we are unable to calculate how much your grade was adjusted."
                )
            else:
                print(
                    f"Your grade was adjusted upwards by {round((adjustment_amount / original_grade) * 100, ndigits=2)}%."
                )

    logging.debug("Main function finished, about to exit.")


if __name__ == "__main__":
    logging.debug("This is the main module and is not being imported.")
    main(args.grade, args.curve)
