#!/usr/bin/env python3
import argparse
import json
import os
from datetime import datetime

parser = argparse.ArgumentParser(
    prog="licence",
    description="Print out a license from a few options",
)
parser.add_argument(
    "licence",
    default="mit",
    nargs="?",
    type=str,
    choices=["apache", "bsd3", "bsd2", "gpl2", "gpl3", "mit", "mozilla2", "epl2"],
    help="The licence to use",
)
parser.add_argument("--name", "-n", help="Copyright holder's name")
args = parser.parse_args()

with open(f"{os.path.dirname(__file__)}/deps/licences.json") as f:
    chosen = json.load(f)[args.licence]

chosen = chosen.replace("<COPYRIGHT HOLDER>", args.name)
chosen = chosen.replace("<YEAR>", str(datetime.now().year))
print(chosen)
