#!/usr/bin/env python3
import argparse
import os

import yaml


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "licence",
        default="mit",
        nargs="?",
        type=str,
        choices=["apache", "bsd3", "bsd2", "gpl2", "gpl3", "mit", "mozilla2", "epl2"],
        help="The licence to use",
    )
    args = parser.parse_args()

    with open(f"{os.path.dirname(__file__)}/licences.yaml") as f:
        licences = yaml.full_load(f)

    print(licences[args.licence])


if __name__ == "__main__":
    main()
