#!python3
import argparse
import random
import string

parser = argparse.ArgumentParser(description="Generate a random password")
parser.add_argument("-l", "--length", default=16, help="Length of the password")
parser.add_argument("-n", "--number", default=1, help="Number of passwords to generate")
parser.add_argument(
    "-s", "--special", action="store_true", help="Do not include special characters"
)
parser.add_argument(
    "-x", "--xkcd", action="store_true", help="Use XKCD style passwords"
)
parser.add_argument("-d", "--dictionary", type=str, default="/usr/share/dict/words")
args = parser.parse_args()


def main(length, number, special, xkcd, dictionary):
    """Generate a random password"""
    chars = string.ascii_letters + string.digits
    if not special:
        chars += string.punctuation

    if xkcd:
        if length == 16:
            length = 4
        words = open(dictionary).read().splitlines()
        for i in range(number):
            print("-".join(random.choice(words) for i in range(length)))
    else:
        for i in range(number):
            password = "".join(random.choice(chars) for i in range(length))
            print(password)


if __name__ == "__main__":
    main(args.length, args.number, args.special, args.xkcd, args.dictionary)
