#!/usr/bin/env python3

import argparse
import random
import string

parser = argparse.ArgumentParser(description="Generate a random password")
parser.add_argument("-l", "--length", default=16, help="Length of the password")
parser.add_argument("-n", "--number", default=1, help="Number of passwords to generate")
parser.add_argument(
    "-s", "--special", action="store_true", help="Do not include special characters"
)
parser.add_argument(
    "-x", "--xkcd", action="store_true", help="Use XKCD style passwords"
)
parser.add_argument("-d", "--dictionary", type=str, default="/usr/share/dict/words")
args = parser.parse_args()

chars = string.ascii_letters + string.digits
if not args.special:
    chars += string.punctuation

if args.xkcd:
    if args.length == 16:
        args.length = 4
    words = open(args.dictionary).read().splitlines()
    for i in range(args.number):
        print("-".join(random.choice(words) for i in range(args.length)))
else:
    for i in range(args.number):
        password = "".join(random.choice(chars) for i in range(args.length))
        print(password)
