#!python3
import os

import click


@click.command()
@click.argument("dir", type=click.Path(exists=True))
def main(dir):
    counter = 0

    # Rename files to numbers
    for file in os.listdir(dir):
        counter += 1
        file_extension = file.split(".")[-1]
        new_name = f"{str(counter)}.{file_extension}"
        os.rename(os.path.join(dir, file), os.path.join(dir, new_name))

    # Get the length of the longest file name
    max_length = len(max(os.listdir(dir), key=len)) + 1

    # Rename files with leading zeros so they are all the same length
    for file in os.listdir(dir):
        file_extension = file.split(".")[-1]
        new_name = f"{file.zfill(max_length)}.{file_extension}"
        os.rename(os.path.join(dir, file), os.path.join(dir, new_name))


if __name__ == "__main__":
    main()
