#!python3
import argparse
import os
import re

parser = argparse.ArgumentParser(
    description="Convert the output of Bible Gateway to simple text files"
)
parser.add_argument("folder", type=str, help="The folder the Bible is in.")
args = parser.parse_args()

os.chdir(args.folder)
for folder in os.listdir():
    if os.path.isdir(folder):
        os.chdir(folder)
        path = os.listdir()
        for file in path:

            with open(file, "r") as f:
                text = f.read()

            lines = text.splitlines()

            for indx, line in enumerate(lines):
                search = re.findall(r"###### (\d+)", line)

                if search:
                    verse = search[0]
                    verse_text = lines[indx + 1]
                    if lines[indx + 2] != "":
                        verse_text += lines[indx + 2]
                    if lines[indx + 3] != "":
                        verse_text += lines[indx + 3]

                    new_file_name = f"{file[:-3]}.{verse}.md"

                    if not os.path.exists(new_file_name):
                        with open(new_file_name, "x") as f:
                            f.write(verse_text)

            os.remove(file)

        # Now sort the files
        folder_name = re.compile(r"^((?:\d )?\w+ \d{1,3})\.\d{1,2}\.md")
        for file in os.listdir():
            move_to = folder_name.match(file)

            if move_to:
                match = move_to.group(1)
                if not os.path.exists(match):
                    os.mkdir(match)

                os.rename(file, f"{match}/{file}")

        os.chdir("..")

names = {
    "1 Chron": "1 Chronicles",
    "2 Chron": "2 Chronicles",
    "1 Cor": "1 Corinthians",
    "2 Cor": "2 Corinthians",
    "Pet": "Peter",
    "1 Sam": "1 Samuel",
    "2 Sam": "2 Samuel",
    "1 Thess": "1 Thessalonians",
    "2 Thess": "2 Thessalonians",
    "Tim": "Timothy",
    "Am": "Amos",
    "Dan": "Daniel",
    "Deut": "Deuteronomy",
    "Eccles": "Ecclesiastes",
    "Ephes": "Ephesians",
    "Esth": "Esther",
    "Exod": "Exodus",
    "Ezek": "Ezekiel",
    "Ezr": "Ezra",
    "Gal": "Galatians",
    "Gen": "Genesis",
    "Hab": "Habakkuk",
    "Hag": "Haggai",
    "Heb": "Hebrews",
    "Hos": "Hosea",
    "Isa": "Isaiah",
    "Jer": "Jeremiah",
    "Josh": "Joshua",
    "Judg": "Judges",
    "Lam": "Lamentations",
    "Lev": "Leviticus",
    "Mal": "Malachi",
    "Matt": "Matthew",
    "Nah": "Nahum",
    "Neh": "Nehemiah",
    "Num": "Numbers",
    "Obad": "Obadiah",
    # "Philem": "Philemon",
    # "Phil": "Philippians",
    "Prov": "Proverbs",
    "Ps": "Psalms",
    "Rev": "Revelation",
    "Rom": "Romans",
    "Song": "Song of Solomon",
    "Zech": "Zechariah",
    "Zeph": "Zephaniah",
}

# Replace the abbreviations with the full name in each path
# First rename the folders
for current_dir, dirs, files in os.walk("."):
    for dir in dirs:
        for name in names:
            if name in dir:
                new_file_name = dir.replace(name, names[name])
                os.rename(dir, new_file_name)

    # Now rename the folders the next level down
    for file in files:
        for name in names:
            if name in file:
                new_file_name = file.replace(name, names[name])
                os.rename(file, new_file_name)
